baseurl = "https://dofler.net/"
languageCode = "en-us"
title = "Dofler"
theme = "creative"
googleAnalytics = ""

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name = "Steven McGrath"
  description = "Dofler Network Sniffing Project"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


  # Navigation
  [params.navigation]
    brand = "<img src=\"img/dofler-header.png\" style=\"position: relative;top: -15px;\"/>"

    [params.navigation.links]
      about     = "About"
      services  = "Technology"
      portfolio = "NaN"
      contact   = "NaN"


  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "<img src=\"img/dofler-logo.png\" width=\"100%\" />"
    #subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
    buttonText = "Install Today!"


  # About section
  [params.about]
    headline    = "What is dofler?"
    description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
    #buttonText  = "Get started!"


  # Service section
  [params.services]
    headline = "Built with things"

        [[params.services.list]]
            icon = "fa-html5"
            title = "HTML Frontend"

        [[params.services.list]]
            icon = "fa-code"
            title = "node.js & python"

        [[params.services.list]]
            icon = "fa-ship"
            title = "docker micro-services"

        [[params.services.list]]
            icon = "fa-server"
            title = "Quick to deploy"


    # Portfolio modals
  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
  [params.aside]
    headline = "Install Dofler Today!"

    [params.aside.button]
      text = "Download now"
      link = "//github.com/stevemcgrath/dofler/"

  # Contact section
  [params.contact]
    headline = "Let's Get In Touch!"
    description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
    phone = "123-456-6789"
    email = "feedback@startbootstrap.com"

  # Google Maps section
  # [params.location]
  #   latitude  = "34.007850"
  #   longitude = "-118.499305"
  #   maps_api_key = ""
