baseurl = "http://dofler.net/"
languageCode = "en-us"
title = "Dofler"
theme = "creative"
googleAnalytics = "UA-79231696-2"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name = "Steven McGrath"
  description = "Dofler Network Sniffing Project"

  favicon = "favicon.ico"
  publishDir = "../docs"


  # Navigation
  [params.navigation]
    brand = "<img src=\"img/dofler-header.png\" style=\"position: relative;top: -15px;\"/>"

    [params.navigation.links]
      about     = "About"
      services  = "Technology"
      #portfolio = "NaN"
      #contact   = "NaN"


  [params.hero]
    slogan     = "<img src=\"img/dofler-logo.png\" width=\"100%\" />"
    buttonText = "Learn More"


  [params.about]
    headline    = "What is dofler?"
    description = """
Dofler is an automated wall of shame designed for general entertainment at conferences.  It has been 
slowly developed over the last several years to include things such as account carving (via ettercap), 
image carving (via driftnet), network stats (via some badly hacked up tshark command), and vulnerability 
sniffing (via [Tenable's very awesome Nessus Network Monitor](http://tenable.com)).  All of this data is then 
aggregated down and presented through an HTML interface.

Dofler got started a few years ago at BSides Chicago (I think it was 2012).  It started as a simple ncurses
front-end to ettercap in a transparent window with the driftnet window sitting behind it.  To say that
it was a hit was an understatement.  People were trolling the system so heavily, I decided to try to make
something a little more scalable.

I originally was going to start by leveraging some of the existing code that people had written for this
exact purpose.  However after looking around, I noticed that most of the code that was in existance was
unmaintained PHP code, and overly complicated hacked together systems.  I wanted something that could be
easy to deploy, scalable, and entertaining to look at.

The continuing effort of that result is what you see today as Dofler.  It's a Python framework that can
be easily extended, supports the ability to have multiple sensors that report back to a single console,
and can support a veriety of the database backends.  Dofler is very much in active development as well
and has undergone several rewrites to help make the code portable and easy to use.

I always welcome any thoughts, suggestions, ideas, code, etc.  Please feel free to contact me through any
of the mechanisms mentioned on my blog [SteveMcGrath.io](http://stevemcgrath.io).
    """


  [params.services]
    headline = "Built with things"

        [[params.services.list]]
            icon = "fa-html5"
            title = "HTML Frontend"

        [[params.services.list]]
            icon = "fa-code"
            title = "node.js & python"

        [[params.services.list]]
            icon = "fa-ship"
            title = "docker micro-services"

        [[params.services.list]]
            icon = "fa-server"
            title = "Quick to deploy"


  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

  [params.aside]
    headline = "Dofler is Open Source!"

    [params.aside.button]
      text = "Github Repository"
      link = "//github.com/stevemcgrath/dofler/"
