version: "3"
services:
  # TODO: Gulp/linting?
  driftnet:
    command: sh -c "npm install && ./node_modules/.bin/nodemon --inspect=0.0.0.0:4001"
    network_mode: bridge # Since Docker on Mac doesn't forward ports with host networking, we set the network mode to bridge
    volumes:
      - ./containers/driftnet/app:/driftnet
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: 'development'
      SPAN_INTERFACE: 'docker0' # As we don't have host networking, we listen to all the other docker container traffic instead