version: "3"
services:
  # TODO: Do we need expose?
  # TODO: Do we need aliases?
  #db:
  #  image: mariadb:latest
  #  volumes:
  #    - ./data/mysql:/var/lib/mysql
  #  networks:
  #    - db

    # TODO: Password etc

  #web:
  #  build: ./containers/web
  #  context: ./containers/web
    #ports:
    #  - 5000:80
  #  networks:
  #    - db
  #    - web
  #  depends_on:
  #    - db

  #images:
  #  networks:
  #    - images
  #    - web
  #  depends_on:
  #    - web

  # TODO: Ramdisk for the temporary image storage?
  driftnet:
    build:
      context: ./containers/driftnet
    networks:
      - images
      - scanner
    cap_add:
      - NET_ADMIN
    #depends_on:
    #  - images

  #ngrep:
  #  networks:
  #    - images
  #  depends_on:
  #    - images
#    cap_add:open_nsfw
#      - NET_ADMIN

  dsniff:
    build:
      context: ./containers/dsniff
    networks:
      - web
      - scanner
    #depends_on:
    #  - web
    cap_add:
      - NET_ADMIN

  ettercap:
    build:
      context: ./containers/ettercap
    networks:
      - web
      - scanner
    #depends_on:
    #  - web
    cap_add:
      - NET_ADMIN

  # tshark:
  #   networks:
  #     - web
  #   depends_on:
  #     - web
#    cap_add:
#      - NET_ADMIN

  # pvs:
  #   networks:
  #     - web
  #   depends_on:
  #     - web
#    cap_add:
#      - NET_ADMIN

networks:
  #database:
  images:
  scanner:
    driver: macvlan
    driver_opts:
      parent: br0

  web:
